Milestone 1
petumazo/CSS-Frameworks pull request #1
Opened 2021-04-06 18:22 UTC by petumazo

Use bootstrap to creat header and footer sections

2021-04-06 19:53 UTC, Dipeshtwis requested changes
# Status:  ♻️ Changes Required ♻️
 Hi @petumazo  and @mariordgez

It's good to see that you have implemented bootstrap very well, but in order to approve, we have to work a little bit more. I have also left some comments.

## To Highlight

- [x] Your Readme file is already looking great. 😊
- [x] Repo looks Professional.

## For Approval

### Header

- [x] The Newsweek logo should have a link.
- [x] Login and Subscribe should have links. Also, the login should be of button type.
- [x] The Newsweek logo looks bigger in tablet mode. See the image below.

![Screenshot (1301)](https://user-images.githubusercontent.com/22434660/113764979-516d9c00-9739-11eb-8681-031f7709ce88.png)

- [x] There is a lot of space in desktop mode. See the image below.

![Screenshot (1302)_LI](https://user-images.githubusercontent.com/22434660/113768661-b5925f00-973d-11eb-8c4e-5be044f82a82.jpg)

### Footer

- [x] The text right to the Newsweek logo is going up. please fix that.

![Screenshot (1302)_LI](https://user-images.githubusercontent.com/22434660/113769710-e9ba4f80-973e-11eb-89d2-20416cf87077.jpg)

## Let's fix all the required change, and we will be done.

(Feel free to contact me on slack by the handle of  **deep** if you have any additional questions).
Happy Coding
[Dipesh Kumar](https://deeptwist.tk) | [Twitter](https://twitter.com/97deepeshkumar)

2021-04-06 19:53 UTC, Dipeshtwis commented on styles/main.css
> +    font-size: 0.7rem;
It should be 768px as per standard.

2021-04-06 19:53 UTC, Dipeshtwis commented on index.html
> +                    </ul>
It should be wrapped in a form with the search field.

2021-04-07 00:38 UTC, Elbie-em requested changes
## STATUS: CHANGES REQUIRED :yellow_circle:

Hello @petumazo and @mariordgez. Great job applying almost all changes requested from the previous review. However, in order for this milestone to be approved, you must complete all changes requested. 

- [x]  The main navigation should have a form with a search field and not a link as you have illustrated. See the comment by the previous TSE.

## [OPTIONAL]

- [x] In regards to content disposition, font sizing and colors in your footer, ensure it corresponds to the original

**Original**
![Screenshot 2021-04-06 at 11 00 45](https://user-images.githubusercontent.com/57832450/113793684-3014ac00-9749-11eb-9e4c-9fce5123d1f9.png)

**Yours**
![Screenshot 2021-04-07 at 02 30 46](https://user-images.githubusercontent.com/57832450/113793763-563a4c00-9749-11eb-835d-32e6e9dfd0ac.png)

### Kindly apply these changes so that we can have this approved. You are doing a great job, keep it up :raised_hands:

*As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 1 code review left for this project. If you think that the code review was not fair, you can request a second opinion using this [form](https://airtable.com/shrQAqnBwek5a0O0s).  *

> Elbie Moonga (Part-time TSE)

> Github (@Elbie-em)
> Slack (Elbie Moonga)
> Twitter ([@ElbieEm](https://twitter.com/ElbieEm))
> LinkedIn([Elbie Moonga](https://www.linkedin.com/in/elbiemoonga/))

2021-04-08 15:37 UTC, petumazo commented
@Dipeshtwis @Elbie-em Thank you so much for your comments and suggestions. They helped us to clean our code and see some missing things we had.

We corrected all your suggestions:

- Add links to The Newsweek logo.
- Use buttons for Login and Subscribe.
- Correct the size of The Newsweek logo in tablet mode.
- Correct the space in desktop mode.
-  Fix the position of the text right to the Newsweek logo.
- Change the size in the CSS to 768px, as per standard.
- Add form with a search field.

Optional:
- We correct font sizing and colors in the footer.

2021-04-09 21:59 UTC, merged